In [ ]:
import pandas as pd
import torch
import torchvision.transforms as transforms
from torchvision.models import vit_b_16, ViT_B_16_Weights
from torch.utils.data import DataLoader 
from torchvision.datasets import ImageFolder 
import numpy as np
from sklearn.metrics import normalized_mutual_info_score
from tqdm import tqdm
from finch import FINCH
from sklearn.cluster import KMeans
from scipy.optimize import linear_sum_assignment

def clustering_accuracy(y_true, y_pred):
    y_true = np.asarray(y_true)
    y_pred = np.asarray(y_pred)

    D = max(y_pred.max(), y_true.max()) + 1
    w = np.zeros((D, D), dtype=np.int64)
    
    for i in range(y_pred.size):
        w[y_pred[i], y_true[i]] += 1

    row_ind, col_ind = linear_sum_assignment(w.max() - w)
    acc = w[row_ind, col_ind].sum() / y_pred.size
    return acc

def extract_features(loader, model):
    features = []
    labels = []
    model.eval()
    with torch.no_grad():
        for images, targets in tqdm(loader, desc="Extracting features"):
            images = images.to(device)
            feat = model(images)
            print("Output shape:", feat.shape)
            features.append(feat.cpu().numpy())
            labels.append(targets.numpy())
    return np.concatenate(features), np.concatenate(labels)

results = []
all_image_info = []

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(f"Using device: {device}")

for trial in range(5):

    unlabeled_transform = transforms.Compose([ 
    transforms.ToTensor(), 
    transforms.Normalize([0.485, 0.456, 0.406], [0.229, 0.224, 0.225]) ])

    unlabeled_folder = fr"C:\Users\HP\novelty\split_datasets\trial_{trial}\42labeled_10unlabeled\unlabeled"

    unlabeled_dataset = ImageFolder(root=unlabeled_folder, transform=unlabeled_transform) 
    print(f"Total gambar dalam unlabeled dataset: {len(unlabeled_dataset)}  {len(unlabeled_dataset.classes)}")

    batch_size = 16

    unlabeled_loader = DataLoader(unlabeled_dataset, batch_size=batch_size, shuffle=False)
    print(f"Total loader gambar dalam unlabeled dataset: {len(unlabeled_loader)}")
    
    model = vit_b_16(weights=ViT_B_16_Weights.IMAGENET1K_V1)
    model.heads = torch.nn.Identity()
    model = model.to(device)
    model.eval()
    
    unlabeled_features, unlabeled_true_labels = extract_features(unlabeled_loader, model)
    
    
    c, num_clust, req_c = FINCH(unlabeled_features, use_ann_above_samples=1000, verbose=True)
    finch_clusters = c[:,2]

    finch_nmi = normalized_mutual_info_score(unlabeled_true_labels, finch_clusters)
    finch_acc = clustering_accuracy(unlabeled_true_labels, finch_clusters)

    print(f"\nFINCH Clustering Performance:")
    print(f"Clustering Accuracy (ACC): {finch_acc:.4f}")
    print(f"Normalized Mutual Information (NMI): {finch_nmi:.4f}")
    print(f"Number of clusters found: {len(np.unique(finch_clusters))}")
    
    num_clusters = len(np.unique(unlabeled_true_labels))
    kmeans = KMeans(n_clusters=num_clusters, random_state=42)
    kmeans_clusters = kmeans.fit_predict(unlabeled_features)

    # ----- Evaluasi -----
    kmeans_nmi = normalized_mutual_info_score(unlabeled_true_labels, kmeans_clusters)
    kmeans_acc = clustering_accuracy(unlabeled_true_labels, kmeans_clusters)

    print(f"\nK-Means Clustering Performance: {num_clusters} Clusters")
    print(f"Clustering Accuracy (ACC): {kmeans_acc:.4f}")
    print(f"Normalized Mutual Information (NMI): {kmeans_nmi:.4f}")
    print(f"Number of clusters found: {len(np.unique(kmeans_clusters))}")
    
    # Simpan hasil trial ini
    results.append({
        'trial': trial,
        'FINCH_ACC': finch_acc,
        'FINCH_NMI': finch_nmi,
        'FINCH_Num_Clusters': len(np.unique(finch_clusters)),
        'KMeans_ACC': kmeans_acc,
        'KMeans_NMI': kmeans_nmi,
        'KMeans_Num_Clusters': len(np.unique(kmeans_clusters)),
    })
    
     # Simpan hasil per gambar
    for i in range(len(unlabeled_dataset)):
        path, true_label = unlabeled_dataset.samples[i]
        image_info = {
            'trial': trial,
            'image_path': path,
            'true_label': true_label,
            'finch_cluster': int(finch_clusters[i]),
            'kmeans_cluster': int(kmeans_clusters[i])
        }
        all_image_info.append(image_info)

    # Simpan file CSV per trial
    df_trial_detail = pd.DataFrame(all_image_info[-len(unlabeled_dataset):])  # ambil data dari trial ini saja
    df_trial_detail.to_csv(f'vit_b_16_pretrained_42labeled_10unlabeled_trial_{trial}_image_clustering.csv', index=False)

# Konversi ke DataFrame dan simpan ke CSV
df_results = pd.DataFrame(results)
mean_values = df_results.select_dtypes(include=np.number).mean()

mean_row = pd.DataFrame({
    'trial': ['Average'],
    'FINCH_ACC': [mean_values['FINCH_ACC']],
    'FINCH_NMI': [mean_values['FINCH_NMI']],
    'FINCH_Num_Clusters': [mean_values['FINCH_Num_Clusters']],
    'KMeans_ACC': [mean_values['KMeans_ACC']],
    'KMeans_NMI': [mean_values['KMeans_NMI']],
    'KMeans_Num_Clusters': [mean_values['KMeans_Num_Clusters']]
})

df_results = pd.concat([df_results, mean_row], ignore_index=True)

df_results.to_csv('clustering_results_vit_b_16_pretrained_42labeled_10unlabeled_FINCH_KMEANS.csv', index=False)
print("Results saved to clustering_results_vit_b_16_pretrained_42labeled_10unlabeled_FINCH_KMEANS.csv")

Using device: cuda
Total gambar dalam unlabeled dataset: 1000  10
Total loader gambar dalam unlabeled dataset: 63


Extracting features:   0%|          | 0/63 [00:00<?, ?it/s]

Output shape: torch.Size([16, 768])


Extracting features:   2%|▏         | 1/63 [00:01<01:22,  1.33s/it]

Output shape: torch.Size([16, 768])


Extracting features:   3%|▎         | 2/63 [00:01<00:54,  1.12it/s]

Output shape: torch.Size([16, 768])


Extracting features:   5%|▍         | 3/63 [00:02<00:43,  1.39it/s]

Output shape: torch.Size([16, 768])


Extracting features:   6%|▋         | 4/63 [00:02<00:38,  1.55it/s]

Output shape: torch.Size([16, 768])


Extracting features:   8%|▊         | 5/63 [00:03<00:34,  1.67it/s]

Output shape: torch.Size([16, 768])


Extracting features:  10%|▉         | 6/63 [00:04<00:32,  1.73it/s]

Output shape: torch.Size([16, 768])


Extracting features:  11%|█         | 7/63 [00:04<00:31,  1.76it/s]

Output shape: torch.Size([16, 768])


Extracting features:  13%|█▎        | 8/63 [00:05<00:30,  1.79it/s]

Output shape: torch.Size([16, 768])


Extracting features:  14%|█▍        | 9/63 [00:05<00:29,  1.82it/s]

Output shape: torch.Size([16, 768])


Extracting features:  16%|█▌        | 10/63 [00:06<00:29,  1.77it/s]

Output shape: torch.Size([16, 768])


Extracting features:  17%|█▋        | 11/63 [00:06<00:28,  1.80it/s]

Output shape: torch.Size([16, 768])


Extracting features:  19%|█▉        | 12/63 [00:07<00:27,  1.85it/s]

Output shape: torch.Size([16, 768])


Extracting features:  21%|██        | 13/63 [00:07<00:27,  1.84it/s]

Output shape: torch.Size([16, 768])


Extracting features:  22%|██▏       | 14/63 [00:08<00:26,  1.86it/s]

Output shape: torch.Size([16, 768])


Extracting features:  24%|██▍       | 15/63 [00:08<00:25,  1.87it/s]

Output shape: torch.Size([16, 768])


Extracting features:  25%|██▌       | 16/63 [00:09<00:25,  1.87it/s]

Output shape: torch.Size([16, 768])


Extracting features:  27%|██▋       | 17/63 [00:09<00:24,  1.88it/s]

Output shape: torch.Size([16, 768])


Extracting features:  29%|██▊       | 18/63 [00:10<00:23,  1.88it/s]

Output shape: torch.Size([16, 768])


Extracting features:  30%|███       | 19/63 [00:11<00:23,  1.86it/s]

Output shape: torch.Size([16, 768])


Extracting features:  32%|███▏      | 20/63 [00:11<00:23,  1.86it/s]

Output shape: torch.Size([16, 768])


Extracting features:  33%|███▎      | 21/63 [00:12<00:22,  1.88it/s]

Output shape: torch.Size([16, 768])


Extracting features:  35%|███▍      | 22/63 [00:12<00:22,  1.86it/s]

Output shape: torch.Size([16, 768])


Extracting features:  37%|███▋      | 23/63 [00:13<00:21,  1.86it/s]

Output shape: torch.Size([16, 768])


Extracting features:  38%|███▊      | 24/63 [00:13<00:20,  1.88it/s]

Output shape: torch.Size([16, 768])


Extracting features:  40%|███▉      | 25/63 [00:14<00:20,  1.88it/s]

Output shape: torch.Size([16, 768])


Extracting features:  41%|████▏     | 26/63 [00:14<00:19,  1.88it/s]

Output shape: torch.Size([16, 768])


Extracting features:  43%|████▎     | 27/63 [00:15<00:19,  1.88it/s]

Output shape: torch.Size([16, 768])


Extracting features:  44%|████▍     | 28/63 [00:15<00:18,  1.87it/s]

Output shape: torch.Size([16, 768])


Extracting features:  46%|████▌     | 29/63 [00:16<00:18,  1.87it/s]

Output shape: torch.Size([16, 768])


Extracting features:  48%|████▊     | 30/63 [00:16<00:17,  1.87it/s]

Output shape: torch.Size([16, 768])


Extracting features:  49%|████▉     | 31/63 [00:17<00:17,  1.88it/s]

Output shape: torch.Size([16, 768])


Extracting features:  51%|█████     | 32/63 [00:17<00:16,  1.87it/s]

Output shape: torch.Size([16, 768])


Extracting features:  52%|█████▏    | 33/63 [00:18<00:16,  1.87it/s]

Output shape: torch.Size([16, 768])


Extracting features:  54%|█████▍    | 34/63 [00:19<00:15,  1.88it/s]

Output shape: torch.Size([16, 768])


Extracting features:  56%|█████▌    | 35/63 [00:19<00:14,  1.87it/s]

Output shape: torch.Size([16, 768])


Extracting features:  57%|█████▋    | 36/63 [00:20<00:14,  1.87it/s]

Output shape: torch.Size([16, 768])


Extracting features:  59%|█████▊    | 37/63 [00:20<00:13,  1.88it/s]

Output shape: torch.Size([16, 768])


Extracting features:  60%|██████    | 38/63 [00:21<00:13,  1.88it/s]

Output shape: torch.Size([16, 768])


Extracting features:  62%|██████▏   | 39/63 [00:21<00:12,  1.88it/s]

Output shape: torch.Size([16, 768])


Extracting features:  63%|██████▎   | 40/63 [00:22<00:12,  1.88it/s]

Output shape: torch.Size([16, 768])


Extracting features:  65%|██████▌   | 41/63 [00:22<00:11,  1.88it/s]

Output shape: torch.Size([16, 768])


Extracting features:  67%|██████▋   | 42/63 [00:23<00:11,  1.88it/s]

Output shape: torch.Size([16, 768])


Extracting features:  68%|██████▊   | 43/63 [00:23<00:10,  1.86it/s]

Output shape: torch.Size([16, 768])


Extracting features:  70%|██████▉   | 44/63 [00:24<00:10,  1.87it/s]

Output shape: torch.Size([16, 768])


Extracting features:  71%|███████▏  | 45/63 [00:24<00:09,  1.88it/s]

Output shape: torch.Size([16, 768])


Extracting features:  73%|███████▎  | 46/63 [00:25<00:09,  1.88it/s]

Output shape: torch.Size([16, 768])


Extracting features:  75%|███████▍  | 47/63 [00:25<00:08,  1.86it/s]

Output shape: torch.Size([16, 768])


Extracting features:  76%|███████▌  | 48/63 [00:26<00:08,  1.87it/s]

Output shape: torch.Size([16, 768])


Extracting features:  78%|███████▊  | 49/63 [00:27<00:07,  1.87it/s]

Output shape: torch.Size([16, 768])


Extracting features:  79%|███████▉  | 50/63 [00:27<00:06,  1.86it/s]

Output shape: torch.Size([16, 768])


Extracting features:  81%|████████  | 51/63 [00:28<00:06,  1.86it/s]

Output shape: torch.Size([16, 768])


Extracting features:  83%|████████▎ | 52/63 [00:28<00:05,  1.86it/s]

Output shape: torch.Size([16, 768])


Extracting features:  84%|████████▍ | 53/63 [00:29<00:05,  1.86it/s]

Output shape: torch.Size([16, 768])


Extracting features:  86%|████████▌ | 54/63 [00:29<00:04,  1.86it/s]

Output shape: torch.Size([16, 768])


Extracting features:  87%|████████▋ | 55/63 [00:30<00:04,  1.84it/s]

Output shape: torch.Size([16, 768])


Extracting features:  89%|████████▉ | 56/63 [00:30<00:03,  1.84it/s]

Output shape: torch.Size([16, 768])


Extracting features:  90%|█████████ | 57/63 [00:31<00:03,  1.84it/s]

Output shape: torch.Size([16, 768])


Extracting features:  92%|█████████▏| 58/63 [00:31<00:02,  1.85it/s]

Output shape: torch.Size([16, 768])


Extracting features:  94%|█████████▎| 59/63 [00:32<00:02,  1.84it/s]

Output shape: torch.Size([16, 768])


Extracting features:  95%|█████████▌| 60/63 [00:32<00:01,  1.84it/s]

Output shape: torch.Size([16, 768])


Extracting features:  97%|█████████▋| 61/63 [00:33<00:01,  1.86it/s]

Output shape: torch.Size([16, 768])


Extracting features:  98%|█████████▊| 62/63 [00:34<00:00,  1.85it/s]

Output shape: torch.Size([8, 768])


Extracting features: 100%|██████████| 63/63 [00:34<00:00,  1.84it/s]


Partition 0: 192 clusters
Partition 1: 38 clusters
Partition 2: 11 clusters
Partition 3: 3 clusters
Dimensi matriks kontingensi (D): 11x11
Matriks kontingensi awal:
[[0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0]]
Matriks kontingensi setelah diisi:
[[ 99   0   0   0  18   0   0   0   0   0   0]
 [  1   0   0   0   0  99   0   0   0   0   0]
 [  0  69   0   0   0   0   0   0   0   0   0]
 [  0  31   0   0   0   0   0   0   0   0   0]
 [  0   0  89   0  82   1   0   0   6   0   0]
 [  0   0  11   0   0   0   0   0  51   0   0]
 [  0   0   0 100   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0 100   0   0   0   0]
 [  0   0   0   0   0   0   0 100   0   0   0]
 [  0   0   0   0   0   0   0   0  43   0   0]
 [  0   0   0   0   0   0   0   0   0 100   0]]
Matrik

In [ ]:
import pandas as pd
import torch
import torchvision.transforms as transforms
from torchvision.models import vit_b_16, ViT_B_16_Weights
from torch.utils.data import DataLoader 
from torchvision.datasets import ImageFolder 
import numpy as np
from sklearn.metrics import normalized_mutual_info_score
from tqdm import tqdm
from finch import FINCH
from sklearn.cluster import KMeans
from scipy.optimize import linear_sum_assignment

def clustering_accuracy(y_true, y_pred):
    y_true = np.asarray(y_true)
    y_pred = np.asarray(y_pred)
    D = max(y_pred.max(), y_true.max()) + 1
    print(f"Dimensi matriks kontingensi (D): {D}x{D}")

    w = np.zeros((D, D), dtype=np.int64)
    print(f"Matriks kontingensi awal:\n{w}")

    for i in range(y_pred.size):
        w[y_pred[i], y_true[i]] += 1
    print(f"Matriks kontingensi setelah diisi:\n{w}")

    cost_matrix = w.max() - w
    print(f"Matriks cost (w.max() - w):\n{cost_matrix}")

    row_ind, col_ind = linear_sum_assignment(cost_matrix)
    print(f"Hasil assignment (row_ind, col_ind): {row_ind}, {col_ind}")

    matched = w[row_ind, col_ind].sum()
    print(f"Total data yang cocok: {matched}/{y_pred.size}")

    accuracy = matched / y_pred.size
    print(f"Akurasi: {accuracy:.4f}")

    return accuracy

def extract_features(loader, model):
    features = []
    labels = []
    model.eval()
    with torch.no_grad():
        for images, targets in tqdm(loader, desc="Extracting features"):
            images = images.to(device)
            feat = model(images)
            print("Output shape:", feat.shape)
            features.append(feat.cpu().numpy())
            labels.append(targets.numpy())
    return np.concatenate(features), np.concatenate(labels)

results = []
all_image_info = []

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(f"Using device: {device}")

for trial in range(1):

    unlabeled_transform = transforms.Compose([ 
    transforms.ToTensor(), 
    transforms.Normalize([0.485, 0.456, 0.406], [0.229, 0.224, 0.225]) ])

    unlabeled_folder = fr"C:\Users\HP\novelty\split_datasets\trial_{trial}\42labeled_10unlabeled\unlabeled"

    unlabeled_dataset = ImageFolder(root=unlabeled_folder, transform=unlabeled_transform) 
    print(f"Total gambar dalam unlabeled dataset: {len(unlabeled_dataset)}  {len(unlabeled_dataset.classes)}")

    batch_size = 16

    unlabeled_loader = DataLoader(unlabeled_dataset, batch_size=batch_size, shuffle=False)
    print(f"Total loader gambar dalam unlabeled dataset: {len(unlabeled_loader)}")
    
    model = vit_b_16(weights=ViT_B_16_Weights.IMAGENET1K_V1)
    model.heads = torch.nn.Identity()
    model = model.to(device)
    model.eval()
    
    unlabeled_features, unlabeled_true_labels = extract_features(unlabeled_loader, model)
    
    
    c, num_clust, req_c = FINCH(unlabeled_features, use_ann_above_samples=1000, verbose=True)
    finch_clusters = c[:,2]

    finch_nmi = normalized_mutual_info_score(unlabeled_true_labels, finch_clusters)
    finch_acc = clustering_accuracy(unlabeled_true_labels, finch_clusters)

    print(f"\nFINCH Clustering Performance:")
    print(f"Clustering Accuracy (ACC): {finch_acc:.4f}")
    print(f"Normalized Mutual Information (NMI): {finch_nmi:.4f}")
    print(f"Number of clusters found: {len(np.unique(finch_clusters))}")
    
    num_clusters = len(np.unique(unlabeled_true_labels))
    kmeans = KMeans(n_clusters=num_clusters, random_state=42)
    kmeans_clusters = kmeans.fit_predict(unlabeled_features)

    # ----- Evaluasi -----
    kmeans_nmi = normalized_mutual_info_score(unlabeled_true_labels, kmeans_clusters)
    kmeans_acc = clustering_accuracy(unlabeled_true_labels, kmeans_clusters)

    print(f"\nK-Means Clustering Performance: {num_clusters} Clusters")
    print(f"Clustering Accuracy (ACC): {kmeans_acc:.4f}")
    print(f"Normalized Mutual Information (NMI): {kmeans_nmi:.4f}")
    print(f"Number of clusters found: {len(np.unique(kmeans_clusters))}")
    
    # Simpan hasil trial ini
    results.append({
        'trial': trial,
        'FINCH_ACC': finch_acc,
        'FINCH_NMI': finch_nmi,
        'FINCH_Num_Clusters': len(np.unique(finch_clusters)),
        'KMeans_ACC': kmeans_acc,
        'KMeans_NMI': kmeans_nmi,
        'KMeans_Num_Clusters': len(np.unique(kmeans_clusters)),
    })
    
     # Simpan hasil per gambar
    for i in range(len(unlabeled_dataset)):
        path, true_label = unlabeled_dataset.samples[i]
        image_info = {
            'trial': trial,
            'image_path': path,
            'true_label': true_label,
            'finch_cluster': int(finch_clusters[i]),
            'kmeans_cluster': int(kmeans_clusters[i])
        }
        all_image_info.append(image_info)

    # # Simpan file CSV per trial
    # df_trial_detail = pd.DataFrame(all_image_info[-len(unlabeled_dataset):])  # ambil data dari trial ini saja
    # df_trial_detail.to_csv(f'vit_b_16_pretrained_42labeled_10unlabeled_trial_{trial}_image_clustering.csv', index=False)

# # Konversi ke DataFrame dan simpan ke CSV
# df_results = pd.DataFrame(results)
# mean_values = df_results.select_dtypes(include=np.number).mean()

# mean_row = pd.DataFrame({
#     'trial': ['Average'],
#     'FINCH_ACC': [mean_values['FINCH_ACC']],
#     'FINCH_NMI': [mean_values['FINCH_NMI']],
#     'FINCH_Num_Clusters': [mean_values['FINCH_Num_Clusters']],
#     'KMeans_ACC': [mean_values['KMeans_ACC']],
#     'KMeans_NMI': [mean_values['KMeans_NMI']],
#     'KMeans_Num_Clusters': [mean_values['KMeans_Num_Clusters']]
# })

# df_results = pd.concat([df_results, mean_row], ignore_index=True)

# df_results.to_csv('clustering_results_vit_b_16_pretrained_42labeled_10unlabeled_FINCH_KMEANS.csv', index=False)
# print("Results saved to clustering_results_vit_b_16_pretrained_42labeled_10unlabeled_FINCH_KMEANS.csv")